import Head from 'next/head'
import Layout from '@/components/Layout'
import { motion } from 'framer-motion'

export default function Terms() {
  return (
    <Layout>
      <Head><title>Terms of Service | OmniDev AI</title></Head>

      <section className="min-h-screen pt-32 pb-20 px-4">
        <div className="max-w-3xl mx-auto">
          <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6 }}>
            <h1 className="text-5xl font-bold text-white mb-4">Terms of <span className="gradient-text">Service</span></h1>
            <p className="text-sm text-slate-500 mb-12">Last updated: January 2025</p>
          </motion.div>

          <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6, delay: 0.2 }}
            className="space-y-8">
            <div className="glass-strong rounded-2xl p-8">
              <h2 className="text-xl font-bold text-white mb-3">1. Acceptance of Terms</h2>
              <p className="text-slate-400 leading-relaxed">By accessing or using OmniDev AI, you agree to be bound by these Terms of Service. If you do not agree, you may not use the platform.</p>
            </div>

            <div className="glass-strong rounded-2xl p-8">
              <h2 className="text-xl font-bold text-white mb-3">2. Account Responsibilities</h2>
              <p className="text-slate-400 leading-relaxed">You are responsible for maintaining the confidentiality of your account credentials. You agree to notify us immediately of any unauthorized use of your account. You must be at least 13 years old to use OmniDev AI.</p>
            </div>

            <div className="glass-strong rounded-2xl p-8">
              <h2 className="text-xl font-bold text-white mb-3">3. Acceptable Use</h2>
              <p className="text-slate-400 leading-relaxed">You may not use OmniDev AI to generate malicious code, exploit vulnerabilities, or engage in any activity that violates applicable laws. AI agent outputs should be reviewed before deployment to production environments.</p>
            </div>

            <div className="glass-strong rounded-2xl p-8">
              <h2 className="text-xl font-bold text-white mb-3">4. Intellectual Property</h2>
              <p className="text-slate-400 leading-relaxed">Code generated by OmniDev AI agents belongs to you. The OmniDev AI platform, branding, and underlying technology remain the intellectual property of OmniDev AI. You retain full ownership of your projects and data.</p>
            </div>

            <div className="glass-strong rounded-2xl p-8">
              <h2 className="text-xl font-bold text-white mb-3">5. Service Availability</h2>
              <p className="text-slate-400 leading-relaxed">We strive for high availability but do not guarantee uninterrupted service. We may modify, suspend, or discontinue features with reasonable notice. Free tier usage may be subject to rate limits.</p>
            </div>

            <div className="glass-strong rounded-2xl p-8">
              <h2 className="text-xl font-bold text-white mb-3">6. Contact</h2>
              <p className="text-slate-400 leading-relaxed">For questions about these terms, contact us at <a href="mailto:legal@omnidev.ai" className="text-purple-400 hover:text-purple-300">legal@omnidev.ai</a>.</p>
            </div>
          </motion.div>
        </div>
      </section>
    </Layout>
  )
}
